In [29]:
import pandas as pd

In [32]:
data_path = r"D:\car-price-prediction\data\eda_vietnamese-car-prices-dataset.csv"
eda_data = pd.read_csv(data_path)

In [33]:
eda_data.head(5)

,names,prices,location,brand,model,year,status,odo,origin,style,transmission,exterior_color,interior_color,seats,doors,drive,description,fuel,volumne
0,Hyundai Tucson 2.0 AT Đặc biệt - 2026,812000000,Hà Nội,Hyundai,Tucson,2026,new,0,assemble,Crossover,auto,black,black,5,5,fwd,"Giá tốt nhất, đăng kí đăng kiểm xe hỗ trợ cho ...",gasonline,2.0
1,Hyundai Palisade Prestige 2.2 AT HTRAC - 2025,1466000000,Hà Nội,Hyundai,Palisade,2025,new,0,assemble,SUV,auto,white,red,6,5,awd,"Giá tốt nhất, đăng kí đăng kiểm xe hỗ trợ cho ...",diesel,2.2
2,Mercedes Benz GLC 300 4Matic - 2023,2278000000,Hồ Chí Minh,Mercedes Benz,GLC,2023,used,19000,assemble,SUV,auto,black,multicolor,5,5,awd,Mercedes GLC300 4Matic 2023 lướt nhẹ 19.000km ...,gasonline,2.0
3,Volkswagen Tiguan Allspace - 2023,1299000000,Hồ Chí Minh,Volkswagen,Tiguan,2023,used,9000,import,SUV,auto,blue,black,7,5,awd,Volkswagen Tiguan All Space siêu lướt 9.000km ...,gasonline,2.0
4,Mercedes Benz GLB 35 4Matic - 2022,1758000000,Hồ Chí Minh,Mercedes Benz,GLB,2022,used,26000,import,SUV,auto,red,black,7,5,awd,ĐAM MÊ TỐC ĐỘ NHƯNG VẪN PHẢI LO CHO GIA ĐÌNH? ...,gasonline,2.0

In [39]:
(eda_data.prices/1000000).median()

np.float64(707.0)

In [ ]:
def process_engine(engine) :
    """
    Hàm này để trích xuất thông tin động cơ thành loại nhiên liệu và dung tích
    """
    def process_fuel(fuel : str) : 
        if fuel.lower() == "xăng" : 
            return "gasonline"
        elif fuel.lower() == "dầu" : 
            return "diesel" 
        elif fuel.lower() == "điện" :
            return "electric"
        return None
    extracted_engine = engine.str.lower().str.strip().str.replace(" l", "").str.split(expand=True)
    extracted_engine.columns = ["fuel", "volumn"]
    extracted_engine["fuel"] = extracted_engine["fuel"].map(process_fuel)
    return extracted_engine

In [32]:
def process_status(status : str) -> str : 
    status = status.lower() 
    if status == "xe đã dùng" : 
        return "used"
    elif status == "xe mới" : 
        return "new"
    return None

0         new
1         new
2        used
3        used
4        used
         ...
24735    used
24736    used
24737    used
24738    used
24739    used
Name: status, Length: 24740, dtype: str

In [29]:
eda_data["interior_color"].value_counts()

interior_color
Đen          12123
Nâu           4120
Kem           3986
Nhiều màu     1332
-              772
Ghi            689
Đỏ             542
Xám            443
Màu khác       178
Vàng           128
Trắng          110
Cam             87
Xanh            85
Bạc             66
Cát             34
Hồng            28
Đồng            12
Tím              5
Name: count, dtype: int64

In [7]:
# PROCESSOR INSTRUCTION 
# 1. Remove Name , Description  
# 2. Map Location Back To New Province
# 3. Because We Know That New Car wont have odo so we remove Status
# 4. Engine we split it into 2 new variables called fuel, volumn
# 5. EDA 
# 6. Encoder 
# 7. Baseline model for regression tasks.

In [ ]:
# EDA INSTRUCTION 
# -> prices (min, max, mean, median, std...)
# -> location (how many provinces, cars for sales by each province)
# -> brand (how much prices by each brand)

In [5]:
eda_data.describe().astype(int)

       Unnamed: 0       prices   year  seats  doors
count       24740        24740  24740  24740  24740
mean        12369   1288481042   2020      5      4
std          7141   1901335291      5      1      0
min             0     10000000   1989      0      0
25%          6184    460000000   2018      5      4
50%         12369    707000000   2022      5      5
75%         18554   1299000000   2024      7      5
max         24739  66000000000   2026     47      5

In [6]:
eda_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 24740 entries, 0 to 24739
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      24740 non-null  int64
 1   names           24740 non-null  str
 2   prices          24740 non-null  int64
 3   location        24740 non-null  str
 4   brand           24740 non-null  str
 5   model           24729 non-null  str
 6   year            24740 non-null  int64
 7   status          24740 non-null  str
 8   odo             19375 non-null  str
 9   origin          24740 non-null  str
 10  style           24740 non-null  str
 11  transmission    24740 non-null  str
 12  engine          24740 non-null  str
 13  exterior_color  24740 non-null  str
 14  interior_color  24740 non-null  str
 15  seats           24740 non-null  int64
 16  doors           24740 non-null  int64
 17  drive           24740 non-null  str
 18  description     24740 non-null  str
dtypes: int64(5), str(14)
memory usage: 3.6 MB

In [11]:
eda_data["location"].nunique()

59